---
- name: Java playbook
  hosts: all
  become: yes
  tasks:
    - name: Update cache
      apt:
       update_cache: yes
    - name: Install Java
      apt:
       name: openjdk-11-jdk
       state: present